# $NetBSD: Makefile,v 1.3 2017/11/23 17:19:57 wiz Exp $

PKGREVISION= 1
.include "../../mate/mate/Makefile.common"

DISTNAME=	mate-calc-${VERSION}
CATEGORIES?=	math mate

COMMENT=	Mate calculator

.include "../../devel/glib2/schemas.mk"
.include "../../textproc/libxml2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
