# $NetBSD$

DISTNAME=	jsonrpclib-pelix-0.3.1
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	mate
MASTER_SITES=	https://pypi.org/packages/source/j/jsonrpclib-pelix/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	https://pypi.org/packages/source/j/jsonrpclib-pelix/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

#WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

PYTHON_VERSION_REQD=    36

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
