# $NetBSD$

PKGNAME=	libf2c-20160102

DISTNAME=	libf2c
CATEGORIES=	mate
MASTER_SITES=	http://www.netlib.org/f2c/
EXTRACT_SUFX=	.zip

MAINTAINER=	nervoso@k1.com.br
HOMEPAGE=	http://www.netlib.org/f2c/
COMMENT=	TODO: Short description of the package

WRKSRC=	${WRKDIR} # More than one possibility -- please check manually.

pre-configure:
	rm ${WRKSRC}/ctype.h
	cd ${WRKSRC};cp makefile.u Makefile

post-build:
	cd ${WRKSRC};make libf2c.so


.include "../../mk/bsd.pkg.mk"
