# $NetBSD: Makefile,v 1.3 2017/11/23 17:19:51 wiz Exp $

PKGREVISION= 1
.include "../../mate/mate/Makefile.common"

DISTNAME=	mate-common-${VERSION}
CATEGORIES?=		devel mate

COMMENT=	Sample files for MATE Application development

.include "../../mk/bsd.pkg.mk"
